name: "mfd0816 ci helpers"
runs:
  using: "composite"
  steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install -y libc++-dev clang-format-20 clang-tidy-20
      shell: bash