name: mfd0816 build
on:
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/depend
      - name: build
        uses: threeal/cmake-action@v2.1.0
        with:
          build-args: -j
          cxx-compiler: ${{ inputs.compiler }}
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.compiler }}-build
          path: build/