name: mfd0816 static checks

on: [workflow_call]

jobs:
  build-cmake:
    name: cmake
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/depend
      - name: build
        uses: threeal/cmake-action@v2.1.0
        with:
          build-args: -j
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-tests
          path: build/test/