name: mfd0816 unit tests

on:
  push:

jobs:
  build-clang:
   uses: ./.github/workflows/build.yml
   with:
     compiler: clang++
  build-gcc:
    uses: ./.github/workflows/build.yml
    with:
      compiler: g++

  doctest-clang:
    needs: build-clang
    runs-on: ubuntu-24.04
    steps:
    - name: get built tests
      uses: actions/download-artifact@v5
      with:
        name: clang++-build
        path: build/
    - name: run
      run: |
        chmod +x -R build
        cd build
        ctest --output-on-failure
  doctest-gcc:
    needs: build-gcc
    runs-on: ubuntu-24.04
    steps:
    - name: get built tests
      uses: actions/download-artifact@v5
      with:
        name: g++-build
        path: build/
    - name: run
      run: |
        chmod +x -R build
        cd build
        ctest --output-on-failure

  static-checks:
    needs: [doctest-clang, doctest-gcc]
    runs-on: ubuntu-24.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - uses: ./.github/actions/depend
    - name: get compilation artifacts
      uses: actions/download-artifact@v5
      with:
        name: clang++-build
        path: build/
    - name: run
      run: |
        git fetch --all
        ln --symbolic "$(which clang-format-20)" /usr/local/bin/clang-format
        ln --symbolic "$(which clang-tidy-20)" /usr/local/bin/clang-tidy
        echo "===== Running static checks for mfdasm ====="
        ./scripts/static-checks.sh asm
        echo
        echo
        echo "===== Running static checks for mfdemu ====="
        ./scripts/static-checks.sh emu
        echo
        echo
        echo "===== Running static checks for shared ====="
        ./scripts/static-checks.sh shared