name: mfd0816 unit tests

on:
  push:

jobs:
  build-clang:
   uses: ./.github/workflows/build.yml
   with:
     compiler: clang++
  build-gcc:
    uses: ./.github/workflows/build.yml
    with:
      compiler: g++

  doctest-clang:
    needs: build-clang
    runs-on: ubuntu-24.04
    steps:
    - name: get built tests
      uses: actions/download-artifact@v5
      with:
        name: clang++-build
        path: build/
    - name: run
      run: |
        chmod +x -R build
        cd build
        ctest --output-on-failure
  doctest-gcc:
    needs: build-gcc
    runs-on: ubuntu-24.04
    steps:
    - name: get built tests
      uses: actions/download-artifact@v5
      with:
        name: g++-build
        path: build/
    - name: run
      run: |
        chmod +x -R build
        cd build
        ctest --output-on-failure

  static-checks:
    needs: [doctest-clang, doctest-gcc]
    runs-on: ubuntu-24.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: get compilation artifacts
      uses: actions/download-artifact@v5
      with:
        name: clang++-build
        path: build/
    - name: run
      run: |
        ./scripts/static-checks.sh asm emu shared