name: mfd0816 unit tests

on:
  push:

jobs:
  static-checks:
    uses: ./.github/workflows/static.yml
  doctest-unittest:
    needs: static-checks
    runs-on: ubuntu-24.04
    steps:
    - name: get built tests
      uses: actions/download-artifact@v5
      with:
        name: built-tests
        path: build/test/
    - name: run
      run: |
        cd build
        ctest --output-on-failure