name: mfd0816 unit tests

on:
  workflow_run:
    workflows: ["mfd0816 static checks"]
    types:
      - completed

jobs:
  doctest-unittest:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: ./.github/actions/depend
    - name: build
      uses: threeal/cmake-action@v2.1.0
      with:
          build-args: -j
          build-dir: build
    - name: run
      run: |
        cd build
        ctest --output-on-failure